### ISSUE TITLE
SEconomy Error.

### ISSUE THREAD

**Issue by TeeriaLLC** [tylerjwatson/SEconomy#4]
No idea what it does or why it is happening, using the Latest SEconomy download from Tshock.co & using the latest Bamboo version #539.

[03/09/16 21:26:16] [Server API] Warning: Plugin "SEconomy (Milestone 1) Update 22 Preview" has had an unhandled exception thrown by one of its GameUpdate handlers: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Wolfje.Plugins.SEconomy.WorldEconomy.GiveRewardsForNPC(NPC NPC)
   at Wolfje.Plugins.SEconomy.WorldEconomy.Game_Update(EventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

I have no idea how to reproduce this, or if it's even relevant.

**Comment by loohney** [comment]
Well it's a warning and not an error. The plugins just says:"Well, something can be wrong here" and not:"Its screwed up!". (:

Also, since its pointing out that Wolfje.Plugins.SEconomy.WorldEconomy.GiveRewardsForNPC(NPC NPC) has something to do with this you should try if earning money from npc's works normally or something happens there too.
