### ISSUE TITLE
SEconomy Jist Error (JistAlias)

### ISSUE THREAD

**Issue by TeeriaLLC** [tylerjwatson/SEconomy#7]
**THIS WAS ORIGINALLY PLACED UNDER THE JIST PLUGIN BUT EVENTUALLY FOUND OUT THAT THIS IS BEING RAN BY SECONOMY.**

Running latest jist release from TShock.co, (SEconomy version 23), don't know whether this is being caused by server running out of memory or by a broken script, would have to look into that.

Using latest TShock Bamboo with broken regions.

```
2016-03-25 16:45:22 - TShock: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
at Wolfje.Plugins.SEconomy.JistAliasModule.JistAlias.d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.b__3(Object state)
at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by TeeriaLLC** [comment]
Updated Newtonsoft.Json.dll to latest version (net45), now threw this error upon user the command /shovel up (/rank up).

```
2016-03-26 17:58:55 - JistEngine: ERROR: JavaScript error: 
at line 2579 column 8

   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Native.JsValue.Invoke(JsValue thisObj, JsValue[] arguments)
   at Wolfje.Plugins.Jist.JistEngine.CallFunction(JsValue function, Object thisObject, Object[] args)
```

Went to the destination and stated this;

```
    if (command == "up") {
        rank_move_next(player, this);   //<---- this line row 8 (begging @ rank_move_next).
        return;
```

Does this mean I did something wrong, or that something in the code is wrong?

**Comment by TeeriaLLC** [comment]
Seem to have found the actual issues this time.

A rank using /shovel up which is not ranked (In this case, guest).

Also confirmed _/jist reload_ **NOT** reloading the script, restart is required.

**Comment by TeeriaLLC** [comment]
Fixed, added permission to the command in the ranking script. This can be closed but could be helpful for new users using SEconomy regarding this matter.
